# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73df1e9a710b158409e68909490505ce892ac2fd97969cb606ad755539a6f37a001ce2e490d01965fd93259fb7ed3e56b981190841f2e56478ce16864f571601

test:
  secret_key_base: 5628b41e8ee09b388aa0dce38d2f390fa02b41e84b58e6d6cabb3f74531c87258f1ca103166bb48ee2f306ef5044ead1795615f16069a557be26ce8bfd4b4141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
